import { AttributeUpdater } from '@kit.ArkUI';

/**
 * @author: HHBin
 * @date: 2024-11-14
 * @desc: 导航动态属性设置
 */
export class NavAnimationModifier extends AttributeUpdater<NavDestinationAttribute, NavDestinationInterface> {
}

export class StackAnimationModifier extends AttributeUpdater<StackAttribute, StackInterface> {
}

export class ImageAnimationModifier extends AttributeUpdater<ImageAttribute, ImageInterface> {
}